# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UK8ex5rmaHlIIRW5bT85IhaeILrFSAe2
"""

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import pandas as pd
import pickle

# =============================
# Load model & encoders
# =============================
try:
    with open("Drug_effect.pkl", "rb") as f:
        model = pickle.load(f)

    with open("onehot_encoder.pkl", "rb") as f:
        ohe = pickle.load(f)

except FileNotFoundError as e:
    raise RuntimeError(f"Missing file: {e}")

# =============================
# FastAPI app
# =============================
app = FastAPI(title="Drug Effect Prediction API")

# =============================
# Input schema
# =============================
class DrugRequest(BaseModel):
    drug_name: str

categorical_features = [
    'drug_name',
    'rx_otc',
    'drug_classes',
    'csa',
    'alcohol',
    'generic_name',
    'medical_condition',
    'activity'
]

# =============================
# Encoding function
# =============================
def encode_input(drug_name: str) -> pd.DataFrame:
    full_input_data = {
        'drug_name': drug_name,
        'rx_otc': 'Unknown',
        'drug_classes': 'Unknown',
        'csa': 'N',
        'alcohol': 'Unknown',
        'generic_name': 'Unknown',
        'medical_condition': 'Unknown',
        'activity': 'Unknown'
    }
    input_df = pd.DataFrame([full_input_data])
    encoded_array = ohe.transform(input_df[categorical_features])
    encoded_df = pd.DataFrame(
        encoded_array,
        columns=ohe.get_feature_names_out(categorical_features),
        index=input_df.index
    )
    return encoded_df

# =============================
# Routes
# =============================
@app.get("/")
def root():
    return {"message": "API running"}

@app.post("/predict")
def predict(request: DrugRequest):
    try:
        df_encoded = encode_input(request.drug_name)
        pred_label = model.predict(df_encoded)[0]
        return {"predicted_pregnancy_category": pred_label}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# =============================
# Run uvicorn when script is executed
# =============================
if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
