// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Diagnosis.Infrastracture.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Diagnosis.Domain.Entites.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirhDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DiagnosisPerDay")
                        .HasColumnType("int");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("FName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("LastResetDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("NationalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Specialization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            BirhDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiagnosisPerDay = 0,
                            ExperienceYears = 8,
                            FName = "Ahmed",
                            IsDeleted = false,
                            LName = "Mahmoud",
                            LastResetDate = new DateOnly(1, 1, 1),
                            ProfileImageUrl = "",
                            Rating = 4.7m,
                            Specialization = "Dermatology",
                            UserId = "user-1"
                        });
                });

            modelBuilder.Entity("Diagnosis.Domain.Entites.MedicalFiles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("FileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalFiles");
                });

            modelBuilder.Entity("Diagnosis.Domain.Entites.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("NotificationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RelatedId")
                        .HasColumnType("int");

                    b.Property<string>("RelatedType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOn")
                        .HasDatabaseName("idx_created_at");

                    b.HasIndex("UserId", "IsRead")
                        .HasDatabaseName("idx_user_unread");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            IsDeleted = false,
                            IsRead = false,
                            Message = "Your appointment is confirmed.",
                            NotificationType = "Appointment",
                            RelatedId = -1,
                            RelatedType = "Appointment",
                            Title = "Appointment Confirmed",
                            UserId = "user-2",
                            UserType = "Patient"
                        });
                });

            modelBuilder.Entity("Diagnosis.Domain.Entites.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allergies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsNewPatient")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsUrgent")
                        .HasColumnType("bit");

                    b.Property<string>("LName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Address = "Cairo",
                            Allergies = "None",
                            BloodType = "A+",
                            DateOfBirth = new DateTime(1996, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FName = "Sara",
                            Gender = "Female",
                            IsDeleted = false,
                            IsNewPatient = true,
                            IsUrgent = false,
                            LName = "Ali",
                            ProfileImageUrl = "",
                            UserId = "user-2"
                        });
                });

            modelBuilder.Entity("Diagnosis.Domain.Entites.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PaymentDate")
                        .HasDatabaseName("idx_payment_date");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Amount = 300m,
                            AppointmentId = -1,
                            DoctorId = -1,
                            IsDeleted = false,
                            Notes = "",
                            PaymentDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Cash",
                            PaymentStatus = "Paid"
                        });
                });

            modelBuilder.Entity("Diagnosis.Domain.Entites.PhysiotherapyExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyPart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YoutubeUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PhysiotherapyExercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BodyPart = "Back",
                            Difficulty = "Easy",
                            DurationMinutes = 4,
                            ThumbnailUrl = "https://img.youtube.com/vi/4BOTvaRaDjI/hqdefault.jpg",
                            Title = "Back Stretch Exercise",
                            YoutubeUrl = "https://www.youtube.com/watch?v=4BOTvaRaDjI"
                        },
                        new
                        {
                            Id = 2,
                            BodyPart = "Back",
                            Difficulty = "Easy",
                            DurationMinutes = 6,
                            ThumbnailUrl = "https://img.youtube.com/vi/DWmGArQBtFI/hqdefault.jpg",
                            Title = "Lower Back Mobility Routine",
                            YoutubeUrl = "https://www.youtube.com/watch?v=DWmGArQBtFI"
                        },
                        new
                        {
                            Id = 3,
                            BodyPart = "Shoulder",
                            Difficulty = "Medium",
                            DurationMinutes = 5,
                            ThumbnailUrl = "https://img.youtube.com/vi/1g6L2HkZz9Y/hqdefault.jpg",
                            Title = "Shoulder Strengthening Exercise",
                            YoutubeUrl = "https://www.youtube.com/watch?v=1g6L2HkZz9Y"
                        },
                        new
                        {
                            Id = 4,
                            BodyPart = "Shoulder",
                            Difficulty = "Medium",
                            DurationMinutes = 7,
                            ThumbnailUrl = "https://img.youtube.com/vi/PPzD2w6pXyE/hqdefault.jpg",
                            Title = "Rotator Cuff Rehab Exercise",
                            YoutubeUrl = "https://www.youtube.com/watch?v=PPzD2w6pXyE"
                        },
                        new
                        {
                            Id = 5,
                            BodyPart = "Legs",
                            Difficulty = "Hard",
                            DurationMinutes = 6,
                            ThumbnailUrl = "https://img.youtube.com/vi/Z8nQXn1pXyE/hqdefault.jpg",
                            Title = "Leg Balance Exercise",
                            YoutubeUrl = "https://www.youtube.com/watch?v=Z8nQXn1pXyE"
                        },
                        new
                        {
                            Id = 6,
                            BodyPart = "Legs",
                            Difficulty = "Medium",
                            DurationMinutes = 5,
                            ThumbnailUrl = "https://img.youtube.com/vi/R1rYz6k2KpU/hqdefault.jpg",
                            Title = "Knee Stability Exercise",
                            YoutubeUrl = "https://www.youtube.com/watch?v=R1rYz6k2KpU"
                        });
                });

            modelBuilder.Entity("Diagnosis.Domain.Models.Entites.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("ReceiveEmailNotifications")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "user-0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0008ce66-58bf-4d06-a864-2104e3d757c2",
                            Email = "admin@diagnosis.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@DIAGNOSIS.COM",
                            NormalizedUserName = "ADMIN@DIAGNOSIS.COM",
                            PasswordHash = "",
                            PhoneNumberConfirmed = false,
                            ReceiveEmailNotifications = true,
                            SecurityStamp = "6296fc3c-30ba-4b71-98a8-b5403102b5b1",
                            TwoFactorEnabled = false,
                            UserName = "admin@diagnosis.com"
                        },
                        new
                        {
                            Id = "user-1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f00860c9-fecd-4c2e-8f58-39f413eb0562",
                            Email = "doctor@test.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR@TEST.COM",
                            NormalizedUserName = "DOCTOR@TEST.COM",
                            PasswordHash = "",
                            PhoneNumberConfirmed = false,
                            ReceiveEmailNotifications = true,
                            SecurityStamp = "stamp1",
                            TwoFactorEnabled = false,
                            UserName = "doctor@test.com"
                        },
                        new
                        {
                            Id = "user-2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9278384e-7943-4f7e-9b61-1356da6207b1",
                            Email = "patient@test.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT@TEST.COM",
                            NormalizedUserName = "PATIENT@TEST.COM",
                            PasswordHash = "",
                            PhoneNumberConfirmed = false,
                            ReceiveEmailNotifications = true,
                            SecurityStamp = "stamp2",
                            TwoFactorEnabled = false,
                            UserName = "patient@test.com"
                        });
                });

            modelBuilder.Entity("Diagnosis.Domain.Models.Entites.ClinicalFinding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiagnosisId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosisId");

                    b.ToTable("ClinicalFindings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiagnosisId = 1,
                            IsDeleted = false,
                            Name = "Body Temperature",
                            Notes = "Fever",
                            Value = "38.5°C"
                        },
                        new
                        {
                            Id = 2,
                            DiagnosisId = 1,
                            IsDeleted = false,
                            Name = "Oxygen Saturation",
                            Notes = "Normal",
                            Value = "98%"
                        },
                        new
                        {
                            Id = 3,
                            DiagnosisId = 2,
                            IsDeleted = false,
                            Name = "Abdominal tenderness",
                            Notes = "Epigastric area",
                            Value = "Present"
                        },
                        new
                        {
                            Id = 4,
                            DiagnosisId = 3,
                            IsDeleted = false,
                            Name = "Blood Pressure",
                            Notes = "Elevated",
                            Value = "150/95 mmHg"
                        },
                        new
                        {
                            Id = 5,
                            DiagnosisId = 4,
                            IsDeleted = false,
                            Name = "HbA1c",
                            Notes = "Above target",
                            Value = "7.1%"
                        },
                        new
                        {
                            Id = 6,
                            DiagnosisId = 4,
                            IsDeleted = false,
                            Name = "Fasting Blood Glucose",
                            Notes = "Elevated",
                            Value = "140 mg/dL"
                        });
                });

            modelBuilder.Entity("Diagnosis.Domain.Models.Entites.Consultation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConfidenceLevel")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiagnosisName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("FileUrls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("RejectNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symptoms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Consultations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConfidenceLevel = 0,
                            Date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "General inquiry about symptoms",
                            DoctorId = -1,
                            IsDeleted = false,
                            Notes = "Patient reports symptoms for 3 days.",
                            PatientId = -1,
                            Status = "Pending",
                            Symptoms = "Headache, fever, and fatigue.",
                            Type = "Inquiry"
                        });
                });

            modelBuilder.Entity("Diagnosis.Domain.Models.Entites.DoctorDiagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientSymptoms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Diagnosises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Viral infection affecting upper respiratory tract",
                            IsDeleted = false,
                            Name = "Upper Respiratory Infection",
                            PatientSymptoms = "Fever, cough, sore throat, runny nose",
                            Title = "Cold & Flu"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Inflammation of stomach lining",
                            IsDeleted = false,
                            Name = "Gastritis",
                            PatientSymptoms = "Abdominal pain, nausea, vomiting",
                            Title = "Stomach Pain"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Chronic elevation of blood pressure",
                            IsDeleted = false,
                            Name = "High Blood Pressure",
                            PatientSymptoms = "Headache, dizziness, blurred vision",
                            Title = "Hypertension"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Routine diabetes follow-up and monitoring",
                            IsDeleted = false,
                            Name = "Type 2 Diabetes Mellitus",
                            PatientSymptoms = "Fatigue, frequent urination",
                            Title = "Diabetes Follow-up"
                        });
                });

            modelBuilder.Entity("Diagnosis.Domain.Models.Entites.Faq", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Faqs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "You can book an appointment through the mobile application.",
                            IsDeleted = false,
                            Question = "How can I book an appointment?",
                            Type = "Patient"
                        },
                        new
                        {
                            Id = 2,
                            Answer = "Yes, you can cancel or reschedule your appointment from your profile.",
                            IsDeleted = false,
                            Question = "Can I cancel or reschedule my appointment?",
                            Type = "Patient"
                        },
                        new
                        {
                            Id = 3,
                            Answer = "Your medical history is available in the medical records section.",
                            IsDeleted = false,
                            Question = "How do I view my medical history?",
                            Type = "Patient"
                        },
                        new
                        {
                            Id = 4,
                            Answer = "Yes, all your data is securely stored and protected.",
                            IsDeleted = false,
                            Question = "Is my personal data secure?",
                            Type = "Patient"
                        },
                        new
                        {
                            Id = 5,
                            Answer = "You can manage your appointments from the doctor dashboard.",
                            IsDeleted = false,
                            Question = "How can I manage my appointments?",
                            Type = "Doctor"
                        },
                        new
                        {
                            Id = 6,
                            Answer = "You can update your availability from your profile settings.",
                            IsDeleted = false,
                            Question = "How do I update my availability?",
                            Type = "Doctor"
                        },
                        new
                        {
                            Id = 7,
                            Answer = "Yes, you can access medical records for patients assigned to you.",
                            IsDeleted = false,
                            Question = "Can I access patient medical records?",
                            Type = "Doctor"
                        },
                        new
                        {
                            Id = 8,
                            Answer = "Payments are transferred to your registered bank account.",
                            IsDeleted = false,
                            Question = "How do I receive payments?",
                            Type = "Doctor"
                        });
                });

            modelBuilder.Entity("Diagnosis.Domain.Models.Entites.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reply")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("Diagnosis.Domain.Models.Entites.SuggestedMedication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiagnosisId")
                        .HasColumnType("int");

                    b.Property<string>("Dosage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosisId");

                    b.ToTable("SuggestedMedications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiagnosisId = 1,
                            Dosage = "500 mg",
                            Frequency = "Every 8 hours",
                            IsDeleted = false,
                            Name = "Paracetamol"
                        },
                        new
                        {
                            Id = 2,
                            DiagnosisId = 1,
                            Dosage = "10 mg",
                            Frequency = "Once daily",
                            IsDeleted = false,
                            Name = "Antihistamine"
                        },
                        new
                        {
                            Id = 3,
                            DiagnosisId = 2,
                            Dosage = "20 mg",
                            Frequency = "Once daily before meals",
                            IsDeleted = false,
                            Name = "Omeprazole"
                        },
                        new
                        {
                            Id = 4,
                            DiagnosisId = 2,
                            Dosage = "10 ml",
                            Frequency = "After meals",
                            IsDeleted = false,
                            Name = "Antacid"
                        },
                        new
                        {
                            Id = 5,
                            DiagnosisId = 3,
                            Dosage = "5 mg",
                            Frequency = "Once daily",
                            IsDeleted = false,
                            Name = "Amlodipine"
                        },
                        new
                        {
                            Id = 6,
                            DiagnosisId = 3,
                            Dosage = "-",
                            Frequency = "Low salt diet & exercise",
                            IsDeleted = false,
                            Name = "Lifestyle modification"
                        },
                        new
                        {
                            Id = 7,
                            DiagnosisId = 4,
                            Dosage = "500 mg",
                            Frequency = "Twice daily",
                            IsDeleted = false,
                            Name = "Metformin"
                        });
                });

            modelBuilder.Entity("Diagnosis.Domain.Models.Entites.SupportTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Reply")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("userId");

                    b.ToTable("SupportTickets");
                });

            modelBuilder.Entity("Diagnosis.Domain.Models.Entites.Symptom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiagnosisId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosisId");

                    b.ToTable("Symptoms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiagnosisId = 1,
                            IsDeleted = false,
                            Name = "Fever"
                        },
                        new
                        {
                            Id = 2,
                            DiagnosisId = 1,
                            IsDeleted = false,
                            Name = "Cough"
                        },
                        new
                        {
                            Id = 3,
                            DiagnosisId = 1,
                            IsDeleted = false,
                            Name = "Sore throat"
                        },
                        new
                        {
                            Id = 4,
                            DiagnosisId = 1,
                            IsDeleted = false,
                            Name = "Runny nose"
                        },
                        new
                        {
                            Id = 5,
                            DiagnosisId = 1,
                            IsDeleted = false,
                            Name = "Body aches"
                        },
                        new
                        {
                            Id = 6,
                            DiagnosisId = 2,
                            IsDeleted = false,
                            Name = "Abdominal pain"
                        },
                        new
                        {
                            Id = 7,
                            DiagnosisId = 2,
                            IsDeleted = false,
                            Name = "Nausea"
                        },
                        new
                        {
                            Id = 8,
                            DiagnosisId = 2,
                            IsDeleted = false,
                            Name = "Vomiting"
                        },
                        new
                        {
                            Id = 9,
                            DiagnosisId = 2,
                            IsDeleted = false,
                            Name = "Bloating"
                        },
                        new
                        {
                            Id = 10,
                            DiagnosisId = 3,
                            IsDeleted = false,
                            Name = "Headache"
                        },
                        new
                        {
                            Id = 11,
                            DiagnosisId = 3,
                            IsDeleted = false,
                            Name = "Dizziness"
                        },
                        new
                        {
                            Id = 12,
                            DiagnosisId = 3,
                            IsDeleted = false,
                            Name = "Blurred vision"
                        },
                        new
                        {
                            Id = 13,
                            DiagnosisId = 4,
                            IsDeleted = false,
                            Name = "Fatigue"
                        },
                        new
                        {
                            Id = 14,
                            DiagnosisId = 4,
                            IsDeleted = false,
                            Name = "Frequent urination"
                        });
                });

            modelBuilder.Entity("Diagnosis.Domain.Models.Entites.TreatmentPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PatientId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatientId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId1");

                    b.ToTable("TreatmentPlans");
                });

            modelBuilder.Entity("Diagnosis.Domain.Models.Entites.UsageConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AiEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaxDiagnosisPerDay")
                        .HasColumnType("int");

                    b.Property<int>("MaxRequestsPerDay")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkHoursPweDoctor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UsageConfig");
                });

            modelBuilder.Entity("Diagnosis.Domain.Models.Entites.UserAIUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("LastResetDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsedRequestsToday")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Usages");
                });

            modelBuilder.Entity("Diagnosis.Domain.Models.Entites.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ReceiveEmailNotifications")
                        .HasColumnType("bit");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role-admin",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "role-doctor",
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = "role-patient",
                            Name = "Patient",
                            NormalizedName = "PATIENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Diagnosis.Domain.Entites.Doctor", b =>
                {
                    b.HasOne("Diagnosis.Domain.Models.Entites.ApplicationUser", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("Diagnosis.Domain.Entites.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Diagnosis.Domain.Entites.MedicalFiles", b =>
                {
                    b.HasOne("Diagnosis.Domain.Entites.Patient", "Patient")
                        .WithMany("Files")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Diagnosis.Domain.Entites.Notification", b =>
                {
                    b.HasOne("Diagnosis.Domain.Models.Entites.ApplicationUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Diagnosis.Domain.Entites.Patient", b =>
                {
                    b.HasOne("Diagnosis.Domain.Models.Entites.ApplicationUser", "User")
                        .WithOne("Patient")
                        .HasForeignKey("Diagnosis.Domain.Entites.Patient", "UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Diagnosis.Domain.Entites.Payment", b =>
                {
                    b.HasOne("Diagnosis.Domain.Entites.Doctor", "Doctor")
                        .WithMany("Payments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Diagnosis.Domain.Models.Entites.ClinicalFinding", b =>
                {
                    b.HasOne("Diagnosis.Domain.Models.Entites.DoctorDiagnosis", "Diagnosis")
                        .WithMany("ClinicalFindings")
                        .HasForeignKey("DiagnosisId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Diagnosis");
                });

            modelBuilder.Entity("Diagnosis.Domain.Models.Entites.Consultation", b =>
                {
                    b.HasOne("Diagnosis.Domain.Entites.Doctor", "Doctor")
                        .WithMany("Consultations")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Diagnosis.Domain.Entites.Patient", "Patient")
                        .WithMany("Consultations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Diagnosis.Domain.Models.Entites.SuggestedMedication", b =>
                {
                    b.HasOne("Diagnosis.Domain.Models.Entites.DoctorDiagnosis", "Diagnosis")
                        .WithMany("SuggestedMedications")
                        .HasForeignKey("DiagnosisId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Diagnosis");
                });

            modelBuilder.Entity("Diagnosis.Domain.Models.Entites.SupportTicket", b =>
                {
                    b.HasOne("Diagnosis.Domain.Entites.Doctor", null)
                        .WithMany("SupportTickets")
                        .HasForeignKey("DoctorId");

                    b.HasOne("Diagnosis.Domain.Entites.Patient", null)
                        .WithMany("SupportTickets")
                        .HasForeignKey("PatientId");

                    b.HasOne("Diagnosis.Domain.Models.Entites.ApplicationUser", "User")
                        .WithMany("SupportTickets")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Diagnosis.Domain.Models.Entites.Symptom", b =>
                {
                    b.HasOne("Diagnosis.Domain.Models.Entites.DoctorDiagnosis", "Diagnosis")
                        .WithMany("Symptoms")
                        .HasForeignKey("DiagnosisId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Diagnosis");
                });

            modelBuilder.Entity("Diagnosis.Domain.Models.Entites.TreatmentPlan", b =>
                {
                    b.HasOne("Diagnosis.Domain.Models.Entites.ApplicationUser", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId");

                    b.HasOne("Diagnosis.Domain.Entites.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId1");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Diagnosis.Domain.Models.Entites.UserAIUsage", b =>
                {
                    b.HasOne("Diagnosis.Domain.Models.Entites.ApplicationUser", "User")
                        .WithOne("Usage")
                        .HasForeignKey("Diagnosis.Domain.Models.Entites.UserAIUsage", "UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Diagnosis.Domain.Models.Entites.UserSettings", b =>
                {
                    b.HasOne("Diagnosis.Domain.Models.Entites.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Diagnosis.Domain.Models.Entites.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Diagnosis.Domain.Models.Entites.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Diagnosis.Domain.Models.Entites.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Diagnosis.Domain.Models.Entites.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Diagnosis.Domain.Entites.Doctor", b =>
                {
                    b.Navigation("Consultations");

                    b.Navigation("Payments");

                    b.Navigation("SupportTickets");
                });

            modelBuilder.Entity("Diagnosis.Domain.Entites.Patient", b =>
                {
                    b.Navigation("Consultations");

                    b.Navigation("Files");

                    b.Navigation("SupportTickets");
                });

            modelBuilder.Entity("Diagnosis.Domain.Models.Entites.ApplicationUser", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("Notifications");

                    b.Navigation("Patient");

                    b.Navigation("SupportTickets");

                    b.Navigation("Usage");
                });

            modelBuilder.Entity("Diagnosis.Domain.Models.Entites.DoctorDiagnosis", b =>
                {
                    b.Navigation("ClinicalFindings");

                    b.Navigation("SuggestedMedications");

                    b.Navigation("Symptoms");
                });
#pragma warning restore 612, 618
        }
    }
}
